### ISSUE TITLE
Update branding

### ISSUE THREAD

**Issue by msoucy** [wilfriedE/FIRSTMastery#7]
A few months ago the branding changed - refer to [FIRST Branding](http://www.firstinspires.org/brand) to get up to date information.

**Comment by wilfriedE** [comment]
With the new branding changes, it looks something like this:
![new_logos](https://cloud.githubusercontent.com/assets/1964213/12226909/920b054a-b7f1-11e5-8cbd-2b33b9edc364.png)

What do you think?, should we keep to these or use the ones with the FIRST Brand logo as shown on  [Branding PDF](http://www.firstinspires.org/sites/default/files/uploads/resource_library/first-brand-guidelines-web-2015.pdf) page 13.

**Comment by msoucy** [comment]
Maybe try using the horizontal ones with the FIRST logo - that way they'll be consistently sized.

**Comment by wilfriedE** [comment]
Looks a little better now, but I think before moving it to production I will reopen this discussion. Should be good on [dev server](http://dev.firstmastery.com/) now.

Preview:
![hrz_logo](https://cloud.githubusercontent.com/assets/1964213/12245531/1be62e4a-b877-11e5-8170-849d51d401ef.png)

There is currently an ongoing issue with Bootstrap-material, but until that's fixed, I've pushed a  temporary fix on the dev server. Thanks for submitting this issue btw. :+1: :metal:
